version: "3.1"

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: pagantis
      MONGO_INITDB_ROOT_PASSWORD: pagantis123
    ports:
      - 27017:27017
    volumes:
      - pagantis-db:/data/db

  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - 8080:8080
    environment:
      MONGO_HOST: mongo
      MONGO_DB: pagantis
      MONGO_USER: pagantis
      MONGO_PASSWORD: pagantis123
      CORS_ORIGINS: http://localhost:3000
    depends_on:
      - mongo
    links:
      - mongo

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      args:
        API_URL: http://localhost:8080/api/
    ports:
      - 3000:80
    links:
      - backend

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: pagantis
      ME_CONFIG_MONGODB_ADMINPASSWORD: pagantis123
    depends_on:
      - mongo
    links:
      - mongo

volumes:
  pagantis-db:
